model_list:
  - model_name: DeepSeek-R1
    litellm_params:
      model: azure/DeepSeek-R1
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: Llama-3.3-70B-Instruct
    litellm_params:
      model: azure/Llama-3.3-70B-Instruct
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: os.environ/AZURE_API_VERSION

  - model_name: claude-haiku-4-5
    litellm_params:
      model: anthropic/claude-haiku-4-5
      api_base: os.environ/AZURE_ANTHROPIC_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: claude-sonnet-4-6
    litellm_params:
      model: anthropic/claude-sonnet-4-6
      api_base: os.environ/AZURE_ANTHROPIC_API_BASE
      api_key: os.environ/AZURE_API_KEY

  - model_name: claude-opus-4-6
    litellm_params:
      model: anthropic/claude-opus-4-6
      api_base: os.environ/AZURE_ANTHROPIC_API_BASE
      api_key: os.environ/AZURE_API_KEY

litellm_settings:
  ssl_verify: /etc/ssl/certs/certbundle.crt

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
